export const SET_ARTISTS = 'SET_ARTISTS';

export const SET_ALBUMS = 'SET_ALBUMS';

export const SET_TRACKS = 'SET_TRACKS';

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const SET_ERROR_STATUS = 'SET_ERROR_STATUS';

export const SET_FAVORITE_ALBUM = 'SET_FAVORITE_ALBUM';

export const REMOVE_FAVORITE_ALBUM = 'REMOVE_FAVORITE_ALBUM';

export const SET_FAVORITE_TRACK = 'SET_FAVORITE_TRACK';

export const REMOVE_FAVORITE_TRACK = 'REMOVE_FAVORITE_TRACK';
